name: NISAR_EA_Workshop_2024_10
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_0
  - aiobotocore=2.15.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.8=py312h66e93f0_0
  - aioitertools=0.12.0=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - asf_search=8.0.1=pyhd8ed1ab_0
  - asf_search-base=8.0.1=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - blosc=1.21.6=hef167b5_0
  - boto3=1.35.23=pyhd8ed1ab_0
  - botocore=1.35.23=pyge310_1234567_0
  - bounded-pool-executor=0.0.3=pyhd8ed1ab_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - ciso8601=2.3.1=py312h66e93f0_1
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312h68727a3_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - dateparser=1.2.0=pyhd8ed1ab_0
  - debugpy=1.8.6=py312h2ec8cdc_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - earthaccess=0.11.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - folium=0.17.0=pyhd8ed1ab_0
  - fonttools=4.54.1=py312h66e93f0_0
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h743c826_0
  - frozenlist=1.4.1=py312h66e93f0_1
  - fsspec=2024.9.0=pyhff2d567_0
  - geopandas=1.0.1=pyhd8ed1ab_1
  - geopandas-base=1.0.1=pyha770c72_1
  - geos=3.13.0=h5888daf_0
  - geotiff=1.7.3=h77b800c_3
  - giflib=5.2.2=hd590300_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py312hb7ab980_102
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - imageio=2.35.1=pyh12aca89_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipympl=0.9.4=pyhd8ed1ab_0
  - ipython=8.27.0=pyh707e725_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.4=hfca40fe_0
  - libblas=3.9.0=24_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=24_linux64_openblas
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgdal-core=3.9.2=hceee5e3_5
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=24_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.44=hadc24fc_0
  - librttopo=1.1.0=h97f6797_17
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=h1b4f908_11
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.7.0=h6565414_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=h4ab18f5_1
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mapclassify=2.8.1=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312h66e93f0_1
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - minizip=4.0.7=h401b404_0
  - multidict=6.1.0=py312h66e93f0_0
  - multimethod=1.12=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - numpy=2.1.1=py312h58c1407_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h1d6d2e6_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h56024de_1
  - pip=24.2=pyh8b19718_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pqdm=0.2.0=pyhd8ed1ab_0
  - proj=9.5.0=h12925eb_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.0.0=py312h66e93f0_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyogrio=0.10.0=py312he8b4914_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyproj=3.7.0=py312he630544_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.6=hc5c86c4_2_cpython
  - python-cmr=0.13.0=pyhd8ed1ab_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.2=pyhd8ed1ab_0
  - pyzmq=26.2.0=py312hbf22597_2
  - qhull=2020.2=h434a139_5
  - rasterio=1.4.1=py312h8456570_0
  - readline=8.2=h8228510_1
  - regex=2024.9.11=py312h66e93f0_0
  - remotezip=0.12.3=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rioxarray=0.17.0=pyhd8ed1ab_0
  - s3fs=2024.9.0=pyhd8ed1ab_0
  - s3transfer=0.10.2=pyhd8ed1ab_0
  - scikit-learn=1.5.2=py312h7a48858_1
  - scipy=1.14.1=py312h7d485d2_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - shapely=2.0.6=py312h391bc85_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - snuggs=1.4.7=pyhd8ed1ab_1
  - sqlite=3.46.1=h9eae976_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinynetrc=1.3.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py312h66e93f0_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h8827d51_1
  - tzlocal=5.2=py312h7900ff3_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - wrapt=1.16.0=py312h66e93f0_1
  - xarray=2024.9.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=h988505b_2
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yarl=1.13.1=py312h66e93f0_0
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
